# Generated by Django 2.2.5 on 2019-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='courses',
            field=models.ManyToManyField(blank=True, to='pages.Course', verbose_name='Выпусники каких курсов интересуют'),
        ),
    ]
