# Generated by Django 2.2.9 on 2020-02-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200114_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='can_full_time',
            field=models.BooleanField(default=False, verbose_name='Полный день'),
        ),
        migrations.AlterField(
            model_name='student',
            name='can_part_time',
            field=models.BooleanField(default=False, verbose_name='Гибкий график'),
        ),
        migrations.AlterField(
            model_name='student',
            name='can_relocate',
            field=models.BooleanField(default=False, verbose_name='Готовность к переезду'),
        ),
        migrations.AlterField(
            model_name='student',
            name='can_remote',
            field=models.BooleanField(default=False, verbose_name='Удаленно'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=127, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(choices=[('NA', 'Не указано'), ('RU', 'Россия'), ('BY', 'Республика Беларусь'), ('KZ', 'Казахстан'), ('UA', 'Украина')], default='NA', max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('0', 'Не указано'), ('m', 'Мужской'), ('f', 'Женский')], default='0', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(blank=True, max_length=127, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='country',
            field=models.CharField(choices=[('NA', 'Не указано'), ('RU', 'Россия'), ('BY', 'Республика Беларусь'), ('KZ', 'Казахстан'), ('UA', 'Украина')], default='NA', max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('0', 'Не указано'), ('m', 'Мужской'), ('f', 'Женский')], default='0', max_length=1, verbose_name='Пол'),
        ),
    ]
