version: '3.7'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
      - frontend

  redis:
    image: "redis:alpine"
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: celery -A app worker -l info
    volumes:
      - ./backend:/home/app/web
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis

  frontend:
    container_name: frontend
    expose:
      - 3000
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: