# Generated by Django 2.2.5 on 2019-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='partners',
            field=models.ManyToManyField(to='users.Partner', verbose_name='Партнеры ждут выпускников'),
        ),
    ]
