# Generated by Django 2.2.9 on 2020-02-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20200210_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('name',), 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AddField(
            model_name='grade',
            name='homework',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.Homework', verbose_name='Домашняя работа'),
            preserve_default=False,
        ),
    ]
