# Generated by Django 2.2.9 on 2020-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student_homework',
            field=models.TextField(default='text', verbose_name='Поле для домашннего задания'),
            preserve_default=False,
        ),
    ]
