# Generated by Django 2.2.9 on 2020-02-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200114_2308'),
        ('education', '0002_grade_student_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='student_homework',
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('student_homework', models.TextField(verbose_name='Поле для домашнего задания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-updated_at'],
            },
        ),
    ]
