from .about_us_page import AboutUsPageAdmin
from .contacts_page import ContactsPageAdmin
from .course import CourseAdmin
from .course_category import CourseCategoryAdmin
from .event import EventAdmin
from .massmedia_publication import MassMediaPublicationAdmin
from .review import ReviewAdmin
from .siteconfiguration import SiteConfigurationAdmin
from .index_page import IndexPageAdmin
